on:
  push:
    branches:
      - 'main'
    paths:
      - 'versions.txt'

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            versions.txt
          ref: 'main'
          path: 'src'
          fetch-depth: 1
          persist-credentials: false

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: 'versions'
          ssh-key: ${{ secrets.CHART_DEPLOY_NO_PHRASE }}
          repository: 'catemlitten/testRepoChart'
          fetch-depth: 30
          persist-credentials: true

      - name: Copy files to chart repo
        shell: bash
        working-directory: versions
        run: |
          ls
          git rev-list head
          mkdir -p versions
          cp -rvT ../src/versions.txt versions/chartVersions.txt

      - name: Check for new files
        working-directory: versions
        shell: bash
        run: |
          pwd
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi
          echo "The value of HAS_CHANGES is $HAS_CHANGES"

      - name: Push new files
        working-directory: versions
        if: env.HAS_CHANGES == 'true'
        shell: bash
        run: |
          git config --global user.name "bot"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git commit -m "updating version from ref: ${{ github.sha }}"
          git push