on:
  push:
    branches:
      - 'main'
    paths:
      - 'versions.txt'

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            versions.txt
          ref: 'main'
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
          ref: 'main'
          repository: 'catemlitten/testRepoChart'
          token: ${{ secrets.CHART_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy files to chart repo
        shell: bash
        run: |
          ls
          cp -rvT versions.txt chartVersions.txt
      - name: Check for new files
        shell: bash
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi
          echo "The value of HAS_CHANGES is $HAS_CHANGES"
      - name: Push new files
        if: env.HAS_CHANGES == 'true'
        shell: bash
        run: |
          git config --global user.name "bot"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git commit -m "updating version from ref: ${{ github.sha }}"
          git push