on:
  push:
    branches:
      - 'main'
    paths:
      - 'versions.txt'

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse_checkout: |
            versions.txt
          ref: 'main'
          persist-credentials: false
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
          ref: 'main'
          repository: 'catemlitten/testRepoChart'
          token: ${{ secrets.CHART_DEPLOY_KEY }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy files to chart repo
        shell: bash
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]];
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::false"
          fi
      - name: Push new files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
        shell: bash
        working-directory: 'dest'
        run: |
          git config --global user.name "bot"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config -m "updating version from ref: ${{ github.sha }}"
          git push