on:
  push:
    branches:
      - 'main'
    paths:
      - 'versions.txt'

jobs:
  copy-files:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            versions.txt
          ref: 'main'
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
          ref: 'main'
          repository: 'catemlitten/testRepoChart'
          token: ${{ secrets.CHART_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy files to chart repo
        shell: bash
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "HAS_CHANGES=true" >> $GITHUB_STATE
          else
            echo "HAS_CHANGES=false" >> $GITHUB_STATE
          fi
      - name: Push new files
        if: HAS_CHANGES == 'true'
        shell: bash
        working-directory: '/'
        run: |
          git config --global user.name "bot"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config -m "updating version from ref: ${{ github.sha }}"
          git push